# 2 - Python e NumPy

In [12]:
#@title Init Cell - Execute-me!!!
pkg = !pip list | grep 'ipynb-autograde'
if not pkg or pkg[0].replace('  ','').split(' ')[1]!='0.0.35':
  !pip install ipynb_autograde==0.0.35
%env  COURSE python_enap
from ipynb_autograde.main import init_log, validate
init_log()
email_result=!gcloud config get-value account
if not email_result or 'unset' in email_result[0]:
  import os
  os.environ['USE_AUTH_EPHEM'] = '0'

  from google.colab import auth
  auth.authenticate_user()

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 233 kB 26.9 MB/s 
     |████████████████████████████████| 63 kB 2.0 MB/s 
  Created wheel for ipynb-autograde: filename=ipynb_autograde-0.0.35-py3-none-any.whl size=934304 sha256=91d58eb21780b4fddedc711d98e31a730aa1252f4106f17d821b45a4183eafe3
  Stored in directory: /root/.cache/pip/wheels/15/f6/e0/39a999df01215b860b10d1b7113af062126ece86501be3c7fc
Successfully built ipynb-autograde
  Attempting uninstall: requests
    Found existing installation: requests 2.23.0
    Uninstalling requests-2.23.0:
      Successfully uninstalled requests-2.23.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires requests~=2.23.0, but you have requests 2.27.1 which is incompatible.
datascience 0.10.6 requires folium==0.2

In [13]:
# Importe as bibliotecas pandas e numpy
import pandas as pd
import numpy as np

### 2.1 Escreva uma função Python para converter para celcius um array de temperaturas em Fahrenheit. Arredonde o resultado até 2a casa decimal usando a função .round(decimals=2) do numpy
#### Exemplo:  para um array([0, 12, 45.21, 34, 99.91])
#### Resultado esperado: array([-17.77, -11.11, 7.33, 1.11, 37.72])
#### Dica 1: a solução pode ser implementada em 1 linha de código
#### Dica 2: T(°C) = (T(°F) - 32) × 5/9
#### Dica 3: Use o conhecimento do slide 13.

In [14]:
# Faca aqui seus testes do Exercício 2.1


In [65]:
# Faca aqui sua função do Exercício 2.1
def get_ceusius(F):
    """retorne um array contendo as temperaturas em graus Ceusius
    """
    return ((F - 32) * (5 / 9)).round(2)

In [66]:
# Faca aqui a validacao do Exercicio 2.1
tf = np.array([0, 12, 45.21, 34, 99.91])
tc = np.array([-17.78, -11.11, 7.34, 1.11, 37.73])
entradas = [[tf]]
saidas = [tc]
validate(get_ceusius, entradas, lambda x: x, saidas, "2.1")

(True, 'Parabéns!')

### 2.2 Escreva uma função Python para somar os valores de cada linha de um array numpy 2D e depois retornar a maior destas somas
#### Exemplo:  para um array([[1  4 ], [10  8], [4  20]]) 
#### Resultado esperado: 24
#### Dica 1: A função ```sum``` do numpy pode fazer o calculo da soma por linha ou por coluna, desde que o parâmetro```axis``` seja especificado corretamente.
#### Dica 2: A função ```max``` do numpy pode retornar o máximo de um array numpy.
#### Dica 3: A solução se resume a duas linhas de código, uma para a soma e outra para o máximo.

In [17]:
# Faca aqui seus testes do Exercício 2.2
def max_sum(x):
    """retorne o valor maximo dentre os resultados da soma por linha de um array 2D 
    """
    return x.sum(axis=1).max()

a1 = np.array([[1, 4 ], [10, 8], [4, 20]])
max_sum(a1)


24

In [18]:
# Faca aqui sua função do Exercício 2.2
def max_sum(x):
    """retorne o valor maximo dentre os resultados da soma por linha de um array 2D 
    """
    return x.sum(axis=1).max()

In [19]:
# Faca aqui a validacao do Exercicio 2.2
a1 = np.array([[1, 4 ], [10, 8], [4, 20]])
a2 = np.array([[1,0,1,9,5],[3,1,2,4,5],[6,1,2,3,4],[8,9,2,1,7]])
entradas = [[a1], [a2]]
saidas = [24, 27]
validate(max_sum, entradas, lambda x: x, saidas, "2.2")

(True, 'Parabéns!')

### 2.3 Escreva uma função Python para contar a quantidade de itens de um dado valor num array NumPy
#### Exemplo:  para um ```array([1  4  10  8  4  20  23])``` e ```n=4```
#### Resultado esperado: 2
#### Dica 1: A função ```count_nonzero``` do pacote numpy conta a quantidade de elementos diferentes de zero ou a quantidade de elementos True.
[https://numpy.org/doc/stable/reference/generated/numpy.count_nonzero.html?highlight=count_nonzero#numpy.count_nonzero](https://numpy.org/doc/stable/reference/generated/numpy.count_nonzero.html?highlight=count_nonzero#numpy.count_nonzero)
#### Dica 2: A solução pode ser implementada em 1 linha de código.
#### Obs.: Lembre-se de usar funções numpy que realizam as operações sem a necessidade de escrever laços (loops)

In [20]:
# Faca aqui seus testes do Exercício 2.3
a1 = np.array([1,0,1,9,5,3,1,2,4,5,6,1,2,3,4,8,9,2,1])

a1[a1 == 1].sum()

5

In [21]:
# Faca aqui sua função do Exercício 2.3
def count_value(array, n):
    """retorne a quantidade de vezes que n ocorre 
    """
    return array[array == n].sum()

In [22]:
# Faca aqui a validacao do Exercicio 2.3
a1 = np.array([1,0,1,9,5,3,1,2,4,5,6,1,2,3,4,8,9,2,1])
entradas = [[a1, 1]]
saidas = [5]
validate(count_value, entradas, lambda x: x, saidas, "2.3")

(True, 'Parabéns!')

### 2.4 Crie uma função que recebe como argumento dois arrays de mesma dimensão e retorna as posições em que esses dois arrays possuem valores coincidentes.
#### Exemplo: Para os arrays a e b abaixo
```a = np.array([1,2,3,2,3,4,3,4,5,6])```

```b = np.array([7,2,10,2,7,4,9,4,9,8])```
#### Resultado esperado: 
```array([1, 3, 5, 7])```

#### Dica: use a função ```np.nonzero```
[https://numpy.org/doc/stable/reference/generated/numpy.nonzero.html#numpy.nonzero](https://numpy.org/doc/stable/reference/generated/numpy.nonzero.html#numpy.nonzero)

In [23]:
# Faca aqui seus testes do Exercício 2.4
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.nonzero(a == b)

(array([1, 3, 5, 7]),)

In [24]:
# Faca aqui sua função do Exercício 2.4
def same_value(arr1, arr2):
    """retorne um array com a posição dos elementos coincidentes nos dois arrays.
    """

    return np.nonzero(arr1 == arr2)


In [25]:
# Faca aqui a validacao do Exercicio 2.4
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.nonzero(a == b)
entradas = [[a, b]]
saidas = [np.array([1, 3, 5, 7])]
validate(same_value, entradas, lambda x: x, saidas, "2.4")

(True, 'Parabéns!')

### 2.5 Escreva uma função Python para selecionar os elementos de um array que são ao mesmo tempo: maiores que 10, menores que 50 e multiplos de 3.
#### Exemplo:  para um array([0, 12, 45, 34, 99])
#### Resultado esperado: array([12, 45])
#### Dica: Reveja a explicação dos slides 22 e 23 da aula 4. 

In [26]:
# Faca aqui seus testes do Exercício 2.5
inarr = np.array([0, 12, 45, 34, 99])
condicao = (inarr > 10) & (inarr < 50) & (inarr % 3 == 0)
inarr[condicao]

array([12, 45])

In [27]:
# Faca aqui sua função do Exercício 2.5
def filter_array(arr):
    """retorne um array numpy contendo números maiores que 10, 
       menores que 50 e multiplos de 3
    """
    condicao = (arr > 10) & (arr < 50) & (arr % 3 == 0)
    return arr[condicao]

In [28]:
# Faca aqui a validacao do Exercicio 2.5
inarr = np.array([0, 12, 45, 34, 99])
outarr = np.array([12, 45])
entradas = [[inarr]]
saidas = [outarr]
validate(filter_array, entradas, lambda x: x, saidas, "2.5")

(True, 'Parabéns!')

### 2.6 Escreva uma função Python para criar um array numpy 2D com 1s nos elementos das bordas e com 0s no interior. O tamanho do array deve ser parametrizável.
#### Exemplo:  para um n=3
#### Resultado esperado: array([[1, 1, 1], [1, 0, 1], [1, 1, 1]])
#### Dica: Crie um array bi-dimensional de zeros (com a função np.zeros) e preencha as bordas com 1s, ou crie um array de 1s (com a função np.ones) e preencha o interior com zeros.

In [40]:
# Faca aqui seus testes do Exercício 2.6
n = 5
arr = np.ones((n, n))
arr[1:-1, 1:-1] = 0

arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [43]:
# Faca aqui sua função do Exercício 2.6
def create_array(n):
    """retorne um array 2d preenchido com 1s nas bordas e 0s no interior 
    """
    arr = np.ones((n, n))
    arr[1:-1, 1:-1] = 0
    return arr

In [44]:
# Faca aqui a validacao do Exercicio 2.6
a3 = np.array([[1, 1, 1], [1, 0, 1], [1, 1, 1]])
a6 = np.array([[1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1.]])

entradas = [[3], [6]]
saidas = [a3, a6]
validate(create_array, entradas, lambda x: x, saidas, "2.6")

(True, 'Parabéns!')

### 2.7 Escreva uma função Python para selecionar dentre os elementos de um array (```arr1``` passado como argumento)  aquele que mais se aproxima de um determinado valor N passado como argumento da função.
#### Se houver dois elementos equidistantes de N e forem os mais próximos de N, retorne o menor. Ou seja, para ```[1, 3, 4]``` e ```N=2```, retorne ```1```.
#### Não use laços (loops), use funções Numpy.
#### Exemplo:  para um ```array([0, 12, 45, 34, 99])``` e ```N=20```
#### Resultado esperado: ```12```
#### Dica 1: Use as funções np.abs, ndarray.argmin e ndarray.sort 
[https://numpy.org/doc/stable/reference/generated/numpy.absolute.html?highlight=abs#numpy.absolute](https://numpy.org/doc/stable/reference/generated/numpy.absolute.html?highlight=abs#numpy.absolute)
[https://numpy.org/doc/stable/reference/generated/numpy.argmin.html?highlight=argmin#numpy.argmin](https://numpy.org/doc/stable/reference/generated/numpy.argmin.html?highlight=argmin#numpy.argmin)
[https://numpy.org/doc/stable/reference/generated/numpy.ndarray.sort.html?highlight=sort#numpy.ndarray.sort](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.sort.html?highlight=sort#numpy.ndarray.sort)
#### Dica 2: Comece ordenando o array com a função ndarray.sort 
#### Dica 3: Crie um array com a diferença entre cada elemento do array de entrada (```arr1```) e o número ```N```, e chame-o de ```dif```. 
#### Dica 4: Calcule o valor absoluto do array ```dif```, e armazene-o numa variável chamada ```absoluto```.
#### Dica 5: De maneira genérica, use uma função numpy para retornar o índice do menor valor de um array, e guarde-o numa variavel chamada ```index```. Este é o índice do elemento do array que mais se aproxima de ```N```. Por que?
#### Dica 6: Retorne o elemento do array ```arr1``` na posição guardada em ```index```.

#### Curiosidade: Por que se faz necessário ordenar o array ```arr1``` ?


In [60]:
# Faca aqui seus testes do Exercício 2.7


4

In [63]:
# Faca aqui sua função do Exercício 2.7
def get_closest(arr1, N):
    """retorne o elemento do array que mais se aproxima de N.
       No caso de dois elementos equidistantes, retorne o menor.
    """
    arr1.sort()
    modulo = abs(arr1 - N)
    indice = np.argmin(modulo)
    valor = arr[indice]
    return valor

In [64]:
# Faca aqui a validacao do Exercicio 2.7
inarr = np.array([3, 6, 1, 4])
entradas = [[inarr, 2]]
saidas = [1]
validate(get_closest, entradas, lambda x: x, saidas, "2.7")

(True, 'Parabéns!')